"use client";

import { useState } from "react";
import { useMailbox } from "./MailboxProvider";
import type { ModerationMode } from "@/types/mailbox";

export default function MailboxAdmin(){
  const {configured,loading,user,member,members,mailbox,invites,error,updateMailbox,createInvite,revokeInvite,setGuestActive}=useMailbox();
  const [email,setEmail]=useState("");const [hours,setHours]=useState(72);const [generated,setGenerated]=useState<{code:string;expires_at:string}|null>(null);const [busy,setBusy]=useState(false);
  const guest=members.find((item)=>item.role==="guest");
  async function generate(){setBusy(true);const result=await createInvite(email,hours);setBusy(false);if(result)setGenerated(result);}
  if(!configured)return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">P3.6 前端已就绪，尚未连接 Supabase。</p><div className="mailbox-admin-status is-offline"><span>○</span><div><b>信鸦通道未配置</b><small>部署数据库和 Edge Function 后，在 GitHub 环境变量中加入两个 NEXT_PUBLIC 配置。</small></div></div></section>;
  if(loading)return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">正在读取邮局状态……</p></section>;
  if(!user)return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">请先从“魔法邮局”页面完成馆主邮箱验证，再返回这里管理邀请与成员。</p></section>;
  if(!member)return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">当前邮箱尚未加入邮局。首次建站请从邮局页面使用馆主建站密钥创建邮局。</p></section>;
  if(member.role!=="owner")return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">你是这座邮局的收信人。邀请、审核和成员设置只对馆主开放。</p></section>;
  return <section className="mailbox-admin"><h3>猫头鹰邮局</h3><p className="admin-lead">管理双人身份、一次性邀请与信笺审核。原始邀请码不会被数据库保存。</p><div className="mailbox-admin-status"><span>●</span><div><b>{mailbox?.name}</b><small>Supabase 已连接 · 馆主身份有效</small></div></div><div className="mailbox-admin-grid"><article><h4>第二位收信人</h4>{guest?<div className="guest-member"><span style={{"--avatar-color":guest.avatar_color} as React.CSSProperties}>{guest.avatar_symbol}</span><div><b>{guest.display_name}</b><small>加入于 {new Date(guest.joined_at).toLocaleDateString("zh-CN")}</small></div><button type="button" onClick={()=>setGuestActive(guest.id,!guest.is_active)}>{guest.is_active?"暂停访问":"恢复访问"}</button></div>:<p>邀请席位尚未使用。</p>}</article><article><h4>审核模式</h4><label className="admin-select-label">新信处理<select value={mailbox?.moderation_mode} onChange={(event)=>updateMailbox({moderation_mode:event.target.value as ModerationMode})}><option value="none">完全私信 · 立即显示</option><option value="first">首次留言审核</option><option value="all">全部留言审核</option></select></label><label className="mailbox-setting-toggle"><input type="checkbox" checked={mailbox?.reactions_enabled??true} onChange={(event)=>updateMailbox({reactions_enabled:event.target.checked})}/>允许魔法反应</label><label className="mailbox-setting-toggle"><input type="checkbox" checked={mailbox?.presence_enabled??true} onChange={(event)=>updateMailbox({presence_enabled:event.target.checked})}/>显示在线状态</label></article></div><article className="invite-maker"><h4>生成一次性邀请咒语</h4><div><label>绑定朋友邮箱<input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="friend@example.com"/></label><label>有效期<select value={hours} onChange={(event)=>setHours(Number(event.target.value))}><option value={24}>24小时</option><option value={72}>72小时</option><option value={168}>7天</option></select></label><button type="button" disabled={busy||!email} onClick={generate}>{busy?"正在封印……":"生成邀请"}</button></div>{generated?<div className="generated-invite"><small>仅本次显示 · 请现在复制并亲自交给朋友</small><strong>{generated.code}</strong><span>有效至 {new Date(generated.expires_at).toLocaleString("zh-CN")}</span><button type="button" onClick={()=>navigator.clipboard.writeText(generated.code)}>复制邀请咒语</button></div>:null}</article>{invites.length?<div className="invite-history"><h4>最近邀请</h4>{invites.map((invite)=><div key={invite.id}><span>{invite.allowed_email_hint??"未绑定邮箱"}</span><time>{new Date(invite.expires_at).toLocaleString("zh-CN")}</time><b>{invite.used_at?"已使用":invite.revoked_at?"已撤销":new Date(invite.expires_at)<new Date()?"已过期":"等待兑换"}</b>{!invite.used_at&&!invite.revoked_at?<button type="button" onClick={()=>revokeInvite(invite.id)}>撤销</button>:null}</div>)}</div>:null}{error?<p className="owl-error" role="alert">{error}</p>:null}</section>;
}
